; (declaration (identifier) @id)
(declaration type: (primitive_type) declarator: (identifier) @id)
(declaration type: (type_identifier) declarator: (identifier) @id)
declarator: (array_declarator declarator: (identifier) @id)
; ↓ this is problematic: int idx = 0;
; declarator: (init_declarator declarator: (identifier) @id)
(declaration (storage_class_specifier) type: (type_identifier) declarator: (init_declarator declarator: (identifier) @id value: (number_literal)))
declarator: (parenthesized_declarator (pointer_declarator declarator: (identifier) @id))
declarator: (init_declarator declarator: (pointer_declarator declarator: (identifier) @id) value: (string_literal))
(declaration (storage_class_specifier) type: (type_identifier) declarator: (init_declarator declarator: (identifier) @id))
(declaration (storage_class_specifier) type: (primitive_type) declarator: (init_declarator declarator: (identifier) @id value: (number_literal)))
(declaration (storage_class_specifier) type: (type_identifier) declarator: (pointer_declarator declarator: (identifier) @id))
(declaration type: (type_identifier) declarator: (pointer_declarator declarator: (identifier) @id))
(declaration (storage_class_specifier) type: (primitive_type) declarator: (pointer_declarator declarator: (identifier) @id))
(declaration (storage_class_specifier) type: (primitive_type) declarator: (init_declarator declarator: (pointer_declarator declarator: (identifier) @id)))
(declaration (storage_class_specifier) type: (type_identifier) declarator: (init_declarator declarator: (pointer_declarator declarator: (identifier) @id)))
(declaration type: (type_identifier) declarator: (init_declarator declarator: (pointer_declarator declarator: (identifier) @id)))
(declaration (storage_class_specifier) type: (struct_specifier name: (type_identifier)) declarator: (pointer_declarator declarator: (identifier) @id))
(declaration type: (struct_specifier name: (type_identifier)) declarator: (pointer_declarator declarator: (identifier) @id))
(declaration (storage_class_specifier) (type_qualifier) type: (struct_specifier name: (type_identifier)) declarator: (init_declarator declarator: (pointer_declarator declarator: (identifier) @id)))
(declaration (storage_class_specifier) type: (sized_type_specifier type: (primitive_type)) declarator: (identifier) @id)
(declaration type: (struct_specifier name: (type_identifier)) declarator: (identifier) @id)
(declaration (storage_class_specifier) type: (primitive_type) declarator: (identifier) @id)
(declaration (storage_class_specifier) type: (struct_specifier name: (type_identifier)) declarator: (init_declarator declarator: (pointer_declarator declarator: (identifier) @id)))
(declaration (storage_class_specifier) type: (sized_type_specifier) declarator: (identifier) @id)
(declaration type: (primitive_type) declarator: (init_declarator declarator: (pointer_declarator declarator: (pointer_declarator declarator: (identifier) @id)) value: (null)))
(declaration (type_qualifier) type: (primitive_type) declarator: (init_declarator declarator: (pointer_declarator declarator: (identifier) @id) value: (null)))
(declaration type: (primitive_type) declarator: (init_declarator declarator: (pointer_declarator declarator: (identifier) @id) value: (null)))
(declaration (storage_class_specifier) type: (primitive_type) declarator: (pointer_declarator declarator: (pointer_declarator declarator: (identifier) @id)))
(declaration (storage_class_specifier) type: (type_identifier) declarator: (pointer_declarator declarator: (pointer_declarator declarator: (identifier) @id)))
(declaration type: (struct_specifier name: (type_identifier)) declarator: (init_declarator declarator: (pointer_declarator declarator: (identifier) @id) value: (null)))
; enum type { VALUE0 } name;
(declaration type: (enum_specifier name: (type_identifier) body: (enumerator_list (enumerator name: (identifier)))) declarator: (identifier) @id)
; static uint8_t name = STATE;
(declaration (storage_class_specifier) type: (primitive_type) declarator: (init_declarator declarator: (identifier) @id value: (identifier)))
; static const int name = CALL(ARG);
(declaration (storage_class_specifier) (type_qualifier) type: (primitive_type) declarator: (init_declarator declarator: (identifier) @id value: (call_expression function: (identifier) arguments: (argument_list))))
; static const type name = CALL(ARG);
(declaration (storage_class_specifier) (type_qualifier) type: (type_identifier) declarator: (init_declarator declarator: (identifier) @id value: (call_expression function: (identifier) arguments: (argument_list))))
; static char **name = NULL;
(declaration (storage_class_specifier) type: (type_identifier) declarator: (init_declarator declarator: (pointer_declarator declarator: (pointer_declarator declarator: (identifier) @id)) value: (null)))
; static struct Struct var = { };
(declaration (storage_class_specifier) type: (struct_specifier name: (type_identifier)) declarator: (init_declarator declarator: (identifier) @id value: (initializer_list)))
; const struct Struct var = { };
(declaration (type_qualifier) type: (struct_specifier name: (type_identifier)) declarator: (init_declarator declarator: (identifier) @id value: (initializer_list)))
